name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 * * 6'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has been open 40 days with no activity. Remove stale label or comment or this will be closed in 10 days. Thank you for your contributions!'
          stale-pr-message: 'This PR has been automatically marked as stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 10 days with no activity. You can always contact the maintainers directly for more information.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity. You can always contact the maintainers directly for more information.'
          days-before-stale: 40
          days-before-pr-stale: 45
          days-before-close: 10
          exempt-issue-assignees: 'thedaviddias'
          exempt-pr-assignees: 'thedaviddias'
          exempt-all-pr-assignees: true
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'keep-unstale,security,dependabot,wip,need-help'
          exempt-issue-labels: 'keep-unstale,security'
          close-issue-label: 'wontfix'
